name: Update Title

on:
  schedule:
<<<<<<< HEAD
    - cron: '*/1 * * * *' # Runs every minute
=======
    - cron: '* * * * *' Runs every minute.
>>>>>>> 569e0c865cea38f22e5e286888d990285ca4fe42

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install with npm
        run: npm install
      - name: Run bot
        run: node index.js
        env:
          dev_api: ${{ secrets.DEV_API_KEY }}
